x-app-common:
  &app-common
  image: transaction_hub:local
  volumes:
    - ".:/transaction-hub-dir"
  env_file:
    - .env

services:
  app:
    << : *app-common
    container_name: transaction_hub__app
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile.local
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - transaction_hub__network
    command: 'runserver.sh'

  db:
    << : *app-common
    image: postgres:17
    container_name: transaction_hub__db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "postgres"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 5s
    networks:
      - transaction_hub__network

volumes:
  postgres_data:
    driver: local

networks:
  transaction_hub__network:
    driver: bridge
